### ISSUE TITLE
Gradients take precedence over hover:bg

### ISSUE THREAD

**Issue by Livijn** [benface/tailwindcss-gradients#21]
Right now, this does not work for me: `bg-gradient-l-green hover:bg-green-500`. The reason is that the gradients set `background-image` while `hover:bg-green-500` set `background-color`.

**Comment by benface** [comment]
Hey @Livijn, thank you for reporting this. I would say that this is actually expected behaviour, because like you said, these utilities don't set the same CSS property. You would need to add `hover:bg-none` to that element's classes in addition to `hover:bg-green-500`. The `bg-none` utility is provided by this plugin, but you have to specify `hover` as a variant for the `backgroundImage` module as it defaults to only `responsive`. Here's how you can do that:
```js
// tailwind.config.js
{
  // ...
  variants: {
    // ...
    backgroundImage: ['hover', 'responsive'],
  },
}
```
